src/ej/urls.py
import logging

from boogie.rest import rest_api
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.core.exceptions import ImproperlyConfigured
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.i18n import set_language
from django.views.static import serve
from ej import services
from ej import views
from ej.fixes import unregister_admin
from ej_boards.api import BoardViewSet
from ej_clusters.api import ClusterizationViewSet
from ej_conversations.api import CommentViewSet, ConversationViewSet, VoteViewSet
from ej_profiles.api import ProfileViewSet
from ej_integrations.api import OpinionComponentViewSet, RasaConversationViewSet
from ej_users.api import TokenViewSet, UsersViewSet
from rest_framework.routers import DefaultRouter
from drf_spectacular.views import SpectacularSwaggerView, SpectacularAPIView
from django.contrib.flatpages import views as flat_views
from django.conf.urls.i18n import i18n_patterns

unregister_admin.unregister_apps()

api_router = DefaultRouter()
api_router.register(
    r"rasa-conversations", RasaConversationViewSet, basename="v1-rasa-conversations"
)
api_router.register(
    r"opinion-component", OpinionComponentViewSet, basename="v1-opinion-component"
)
api_router.register(r"conversations", ConversationViewSet, basename="v1-conversations")
api_router.register(r"comments", CommentViewSet, basename="v1-comments")
api_router.register(r"votes", VoteViewSet, basename="v1-votes")
api_router.register(
    r"clusterizations", ClusterizationViewSet, basename="v1-clusterizations"
)
api_router.register(r"profiles", ProfileViewSet, basename="v1-profiles")
api_router.register(r"boards", BoardViewSet, basename="v1-boards")
api_router.register(r"users", UsersViewSet, basename="v1-users")
api_router.register(r"", TokenViewSet, basename="v1-auth")

log = logging.getLogger("ej")


def get_apps_dynamic_urls():
    """
    Allows apps to include new urls without editing ej/urls.py directly.
    In order to include new urls, the app must implements the get_app_urls method,
    inside the apps.py file. The method must return a namespaced path, for example:

    def get_app_urls(self):
        from my_app.views import View
        from django.urls import path

        urlpatterns = [path("path/", View.as_view(), name="path")]
        return path("customapp/", include(urlpatterns, namespace="customapp"))

    Checks ej_activation app, for example.
    """
    apps_urls = []
    for app_config in apps.app_configs:
        try:
            get_app_urls = getattr(apps.app_configs[app_config], "get_app_urls")
            apps_urls += [get_app_urls()]
            log.info(f"Including {app_config} URLs using get_apps_dynamic_urls()")
        except Exception:
            pass
    return apps_urls


def get_urlpatterns():
    fixes()

    patterns = [
        #
        # Basic authentication and authorization
        path(
            "",
            views.IndexView.as_view(),
            name="index",
        ),
        path(
            "info/styles/",
            views.InfoStylesView.as_view(),
            name="info-styles",
        ),
        path(
            "info/django-settings/",
            views.InfoDjangoSettingsView.as_view(),
            name="info-django-settings",
        ),
        path(
            "info/environment/",
            views.InfoEnvironView.as_view(),
            name="info-environ",
        ),
        path(
            "sw.js",
            views.ServiceWorkerView.as_view(),
            name="service-worker",
        ),
        path("", include("ej_users.urls.user", namespace="auth")),
        path("", include("ej_users.urls.account", namespace="account")),
        #
        #  Conversations and other EJ-specific routes
        path(
            "conversations/",
            include(
                "ej_conversations.urls.public_conversations", namespace="conversation"
            ),
        ),
        path(
            "comments/", include("ej_conversations.urls.comments", namespace="comments")
        ),
        #
        #  Profile URLS
        path("profile/", include("ej_profiles.urls", namespace="profile")),
        #
        #  Data visualization
        path("conversations/", include("ej_dataviz.urls", namespace="dataviz")),
        #
        # Administration Routes
        path("administration/", include("ej_admin.urls", namespace="administration")),
        #
        #  Global stereotype and cluster management
        path("conversations/", include("ej_clusters.urls.clusters", namespace="cluster")),
        path(
            "conversations/",
            include("ej_clusters.urls.stereotype_votes", namespace="stereotype-votes"),
        ),
        path(
            "stereotypes/",
            include("ej_clusters.urls.stereotypes", namespace="stereotypes"),
        ),
        #
        # Localization Routes
        path("change-language/", set_language, name="set_language"),
        #
        # Documentation in development mode
        re_path(r"^docs/$", serve, {"document_root": "build/docs", "path": "index.html"}),
        re_path(r"^docs/(?P<path>.*)$", serve, {"document_root": "build/docs/"}),
        #
        #  Admin
        *(
            [path(fix_url(settings.ADMIN_URL.lstrip("/")), admin.site.urls)]
            if apps.is_installed("django.contrib.admin")
            else ()
        ),
        path("usage", flat_views.flatpage, {"url": "usage"}, name="Terms of use"),
        # Boards URLs
        path("boards/", include("ej_boards.urls", namespace="boards")),
        #
        #  Allauth
        path("accounts/", include("allauth.urls")),
        #
        # REST API
        path("api/v1/", include(api_router.urls)),
        path("api/", include(rest_api.urls)),
        path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
        path(
            "api/v1/swagger/",
            SpectacularSwaggerView.as_view(url_name="schema"),
            name="swagger",
        ),
        # Static files for the dev server
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
        *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
        *get_apps_dynamic_urls(),
    ]

    if settings.DEBUG:
        # Pages for error codes
        patterns.extend(
            [
                path(
                    "error/400/",
                    default_views.bad_request,
                    kwargs={"exception": Exception("Bad Request!")},
                ),
                path(
                    "error/403/",
                    default_views.permission_denied,
                    kwargs={"exception": Exception("Permission Denied")},
                ),
                path(
                    "error/404/",
                    default_views.page_not_found,
                    kwargs={"exception": Exception("Page not Found")},
                ),
                path("error/500/", default_views.server_error),
                path("roles/", include("ej.roles.routes")),
            ]
        )

        if "debug_toolbar" in settings.INSTALLED_APPS:
            import debug_toolbar

            patterns.append(path("__debug__/", include(debug_toolbar.urls)))
    return patterns


def fix_url(url):
    return url.strip("/") + "/"


def fixes():
    if not apps.is_installed("ej_users"):
        user = get_user_model()
        try:
            rest_api.get_resource_info(user)
        except ImproperlyConfigured:
            rest_api(["username"])(user)


services.start_services(settings)
urlpatterns = get_urlpatterns()

src/ej_conecta_trabalhadores/urls.py
from django.urls import path

from .views import (
    ConectaConversationCommentView,
    EndParticipationView,
    RegisterProfileView,
    RegisterView,
    TourView,
    WelcomeView,
)

app_name = "ej_conecta_trabalhadores"
app_url = "conecta"
conversation_url = (
    "boards/<slug:board_slug>/conversations/<int:conversation_id>/<slug:slug>"
)

urlpatterns = [
    path(
        f"{app_url}/register",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        f"{app_url}/{conversation_url}/profile",
        RegisterProfileView.as_view(),
        name="profile",
    ),
    path(
        f"{app_url}/{conversation_url}/participe",
        WelcomeView.as_view(),
        name="welcome",
    ),
    path(
        f"{app_url}/{conversation_url}/encerrar",
        EndParticipationView.as_view(),
        name="end-participation",
    ),
    path(
        f"{app_url}/profile/tour/",
        TourView.as_view(),
        name="tour",
    ),
    path(
        f"{app_url}/profile/tour/?step=<step>",
        TourView.as_view(),
        name="tour",
    ),
    path(
        f"{app_url}/{conversation_url}/comments/new/",
        ConectaConversationCommentView.as_view(),
        name="new-comment",
    ),
]

src/ej_conversations/models/comment.py
from django.db import models
from hashlib import blake2b
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from model_utils.choices import Choices
from model_utils.models import TimeStampedModel, StatusModel

from .comment_queryset import CommentQuerySet, log
from .vote import Vote
from ..enums import Choice, RejectionReason
from ..signals import vote_cast
from ..utils import votes_counter
from ..validators import is_not_empty


class Comment(StatusModel, TimeStampedModel):
    """
    A comment on a conversation.
    """

    STATUS = Choices(
        ("pending", _("awaiting moderation")),
        ("approved", _("approved")),
        ("rejected", _("rejected")),
    )
    STATUS_MAP = {
        "pending": STATUS.pending,
        "approved": STATUS.approved,
        "rejected": STATUS.rejected,
    }

    conversation = models.ForeignKey(
        "Conversation", related_name="comments", on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="comments", on_delete=models.CASCADE
    )
    content = models.TextField(
        _("Content"),
        max_length=252,
        validators=[MinLengthValidator(2), is_not_empty],
        help_text=_("Body of text for the comment"),
    )
    rejection_reason = models.IntegerField(
        choices=RejectionReason.choices, default=RejectionReason.USER_PROVIDED
    )
    rejection_reason_text = models.TextField(
        _("Rejection reason (free-form)"),
        blank=True,
        help_text=_(
            "You must provide a reason to reject a comment. Users will receive "
            "this feedback."
        ),
    )
    moderator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="moderated_comments",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    is_approved = property(lambda self: self.status == self.STATUS.approved)
    is_pending = property(lambda self: self.status == self.STATUS.pending)
    is_rejected = property(lambda self: self.status == self.STATUS.rejected)

    @property
    def has_rejection_explanation(self):
        return self.rejection_reason != RejectionReason.USER_PROVIDED or (
            self.rejection_reason.USER_PROVIDED and self.rejection_reason_text
        )

    @property
    def author_name(self):
        return self.author.name

    @property
    def missing_votes(self):
        return self.conversation.users.count() - self.n_votes

    @property
    def skip_count(self):
        return votes_counter(self, choice=Choice.SKIP)

    @property
    def disagree_count(self):
        return votes_counter(self, choice=Choice.DISAGREE)

    @property
    def agree_count(self):
        return votes_counter(self, choice=Choice.AGREE)

    @property
    def n_votes(self):
        return votes_counter(self)

    @property
    def rejection_reason_display(self):
        if self.status == self.STATUS.approved:
            return _("Comment is approved")
        elif self.status == self.STATUS.pending:
            return _("Comment is pending moderation")
        elif self.rejection_reason_text:
            return self.rejection_reason_text
        elif self.rejection_reason is not None:
            return self.rejection_reason.description
        else:
            raise AssertionError

    objects = CommentQuerySet.as_manager()

    class Meta:
        unique_together = ("conversation", "content")

    def __str__(self):
        return self.content

    def clean(self):
        super().clean()
        if self.status == self.STATUS.rejected and not self.has_rejection_explanation:
            raise ValidationError(
                {"rejection_reason": _("Must give a reason to reject a comment")}
            )

    def vote(self, author, choice, channel="ej", commit=True):
        """
        Cast a vote for the current comment. Vote must be one of 'agree', 'skip'
        or 'disagree'.

        >>> comment.vote(user, 'agree')                         # doctest: +SKIP
        """

        choice = Choice.normalize(choice)

        if self.is_pending:
            raise (ValidationError(_("Cannot vote on pending comment")))

        # We do not full_clean since the uniqueness constraint will only be
        # enforced when strictly necessary.
        vote = Vote(author=author, comment=self, choice=choice, channel=channel)
        vote.clean_fields()

        # Check if vote exists and if its existence represents an error
        is_changed = False
        try:
            saved_vote = Vote.objects.get(author=author, comment=self)
        except Vote.DoesNotExist:
            pass
        else:
            if saved_vote.choice == choice:
                commit = False
            elif saved_vote.choice == Choice.SKIP:
                vote.id = saved_vote.id
                vote.created = now()
                is_changed = True
            else:
                raise ValidationError("Cannot change user vote")

        # Send possibly saved vote
        if commit:
            vote.save()
            log.debug(f"Registered vote: {author} - {choice}")
            vote_cast.send(
                Comment,
                vote=vote,
                comment=self,
                choice=choice,
                is_update=is_changed,
                is_final=choice != Choice.SKIP,
            )
        return vote

    def statistics(self, ratios=False):
        """
        Return full voting statistics for comment.

        Args:
            ratios (bool):
                If True, also include 'agree_ratio', 'disagree_ratio', etc
                fields each original value. Ratios count the percentage of
                votes in each category.

        >>> comment.statistics()                            # doctest: +SKIP
        {
            'agree': 42,
            'disagree': 10,
            'skip': 25,
            'total': 67,
            'missing': 102,
        }
        """

        stats = {
            "agree": self.agree_count,
            "disagree": self.disagree_count,
            "skip": self.skip_count,
            "total": self.n_votes,
            "missing": self.missing_votes,
        }

        if ratios:
            e = 1e-50  # prevents ZeroDivisionErrors
            stats.update(
                agree_ratio=self.agree_count / (self.n_votes + e),
                disagree_ratio=self.disagree_count / (self.n_votes + e),
                skip_ratio=self.skip_count / (self.n_votes + e),
                missing_ratio=self.missing_votes
                / (self.missing_votes + self.n_votes + e),
            )
        return stats

    def comment_url_hash(self):
        """
        Compute the URL hash for the given comment.
        """
        return blake2b(self.content.encode("utf8"), digest_size=4).hexdigest()

    def next(self, current_index, comments):
        """
        Get next comment of a conversation, according to create date
        """
        next_index = current_index + 1
        id = None

        try:
            id = comments[next_index]["comment"]
        except IndexError:
            pass

        return id

    def previous(self, current_index, comments):
        """
        Get previous comment of a conversation, according to create date
        """
        previous_index = current_index - 1
        id = None

        try:
            id = comments[previous_index]["comment"]
        except IndexError:
            pass

        if previous_index < 0:
            id = None

        return id

src/ej_conecta_trabalhadores/templates/jinja2/ej_conversations/comments/add-comment.jinja2
{% from "ej_conversations/includes/toast.jinja2" import dialog %}

{{ dialog("comment-dialog-confirmation", _("Thank you! Your comment was sent to moderation and will be evaluated soon."))}}
<div class="add-comment-form">
    {% if user == None %}
        <p>{% trans %}Please <a href="{{ login_anchor }}">login</a> to vote on this conversation.{% endtrans %}</p>
    {% elif not user_can_add_comments %}
        <h3>{% trans %}Ooops!{% endtrans %}</h3>
        <p>{% trans %}You reached the limit of comments in this conversation.{% endtrans %}</p>
    {% else %}
        <div class="col margin-y3 pad-x2" id="comment-card">
                <h1 class="text-accent left conecta-icon">
                    <i class="fa">&#xf055;</i>
                    {{ _('I want to add my ideia!') }}
                </h2>
                <form id="add-comment-form"
                    class="width-full"
                    hx-post="{{ url('conecta:new-comment', **conversation.get_url_kwargs()) }}"
                    hx-target=".add-comment-form"
                    hx-swap="outerHTML"
                >
                    {{ csrf_input }}
                    <input type="hidden" name="action" value="comment" placeholder="{{_('Enter your proposal for the question that appears on this screen here.')}}">
                    {{ form.non_field_errors() }}
                    {{ form.content.errors }}
                    <textarea name="content" cols="40" rows="5" maxlength="252"
                        placeholder="{{_('Type here your answer to the question: ') + conversation.text }}"
                        title="Sugira um novo comentário" required="" id="id_content"
                    ></textarea>
                    <button  class="is-primary button" type="submit" aria-label="{{ _('Send') }}">{{ _('Send') }}</button>
                </form>
        </div>
    {% endif %}
</div>

<script>
    $("#add-comment-form").on("htmx:afterRequest", () => {
        showConfirmationDialogFor("#comment-dialog-confirmation")
        $("textarea")[0].value = "";
    });
</script>

src/ej_conecta_trabalhadores/templates/jinja2/ej_conversations/comments/card.jinja2
{% if user_can_participate %}

    <div id="comment-content-container">
        {% from "ej_conversations/includes/toast.jinja2" import dialog %}
        {{ dialog("voting-dialog-confirmation", _("Thanks for voting.")) }}

        <div class="conecta-vote-card">
            {% include 'ej_conversations/includes/conversation-header.jinja2' %}
        </div>

        <div class="conecta-comment-grid">
            <div class="comment-card">
                <article>
                    <div class="comment-card__subtitle">{{(_("Other people suggested the following ideia:"))}}</div>
                    <div class="comment">
                        <p class="comment__text">
                            {{ comment.content }}
                        </p>
                        <div class="comment-card__gradient"></div>
                    </div>
                </article>

                <form id="voting-form"
                    class="width-full"
                    hx-trigger="click delay:1.5s"
                    hx-post="{{ url('boards:conversation-detail', **conversation.get_url_kwargs()) }}"
                    hx-target="#comment-content-container" hx-swap="outerHTML">
                    {{ csrf_input }}
                    <input type="hidden" name="vote" value="">
                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                        <div class="comment-card__button">
                            <button onclick="showSpinner('agree')"
                                    name="vote"
                                    value="agree"
                                    form="voting-form">
                                <img src="/static/img/vote/solve.svg">
                                <span id="agree-spinner" style="display: none" class="conecta-loader"></span>
                            </button>
                            <span>{{_("Solve")}}</span>
                        </div>
                        <div class="comment-card__button">
                            <button
                                    onclick="showSpinner('disagree')"
                                    name="vote"
                                    value="disagree"
                                    form="voting-form">
                                <img src="/static/img/vote/no-solve.svg">
                                <span id="disagree-spinner" style="display: none" class="conecta-loader"></span>
                            </button>
                            <span>{{_("It does not solve")}}</span>
                        </div>
                        <div class="comment-card__button">
                            <button onclick="showSpinner('skip')"
                                    name="vote"
                                    value="skip"
                                    form="voting-form">
                                <img src="/static/img/vote/doubt.svg">
                                <span id="skip-spinner" style="display: none" class="conecta-loader"></span>
                            </button>
                            <span>{{_("I am in doubt")}}</span>
                        </div>
                </form>
                <div class="comment-card__progress">
                    <div>
                        {{ n_user_final_votes }} {{_("of")}} {{ conversation.n_approved_comments }} {{_("ideias")}}
                    </div>
                </div>
            </div>
        </div>
        <script>

            $("#voting-form").on("htmx:afterRequest", () => {
                if (event.target.id == 'voting-form' && event.detail.successful){
                    showConfirmationDialogFor("#voting-dialog-confirmation")
                }
            });

            function setVoteInputChoice(choice) {
                $("input[name='vote']")[0].value = choice;
            }

            function disableButtonsDuringRequest() {
                buttons = $("form").find("button");
                for (let button of buttons) {
                    button.disabled = true;
                }
            }

            function showSpinner(choice) {
                setVoteInputChoice(choice);
                disableButtonsDuringRequest();
                let voteOptionImg = $(`button[value=${choice}] img`)
                voteOptionImg.addClass("comment-card__button--hidden");
                let spinner = $(`#${choice}-spinner`);
                spinner.addClass("show");
            }
        </script>
    </div>

{% else %}
    {% include 'ej_users/conecta-register.jinja2' %}
{% endif %}

src/ej_conecta_trabalhadores/templates/jinja2/ej_conversations/comments/conclusion-card.jinja2
<div id="comment-content-container">
    {% from "ej_conversations/includes/toast.jinja2" import dialog %}
    <dialog class="toast toast--hide" id="share-conversation-dialog-confirmation">
        <div class="toast__content">
            <span>{{_("Link copied to clipboard")}}</span>
        </div>
    </dialog>
    <div id="comment-content-container">
        <div class="conecta-vote-card">
            {% include 'ej_conversations/includes/conversation-header.jinja2' %}
        </div>
        <div class="conecta-comment-grid">
            <div class="conecta-finish-vote comment-card">
                <article>
                    <p class="comment__text comment__text--center">
                        {{_("You have already reacted to all the proposals made for this question.")}}
                    </p>
                    <p class="comment__text comment__text--center comment__text--small">
                        {{_("Click on share button to copy the conversation link and send it to your comunity.")}}
                    </p>
                    <div class="margin-y4 margin-xauto conecta-buttons flex justify-center">
                        <div class="margin-xauto profile-btn">
                            <button type="button"
                                    id="finish-voting-button"
                                    onclick="conectaShare()"
                                class="width-full conecta-buttons--share conecta-buttons--is-primary-purple">
                                <i class="fas fa-link"></i>
                                {{_("Share this research")}}
                            </button>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
    {% include 'ej_conversations/comments/add-comment.jinja2' %}
    <script>
    function conectaShare(){
        const url = `${window.location.pathname}`;
        const updatedUrl = url.replace(/profile\/?$/, '');
        let link = `${window.location.origin}/conecta${updatedUrl}participe`;
        navigator.clipboard.writeText(link).then(() => {
            showConfirmationDialogFor("#share-conversation-dialog-confirmation");
        });
    }
    </script>
</div>