src/ej/urls.py
import logging

from boogie.rest import rest_api
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.core.exceptions import ImproperlyConfigured
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.i18n import set_language
from django.views.static import serve
from ej import services
from ej import views
from ej.fixes import unregister_admin
from ej_boards.api import BoardViewSet
from ej_clusters.api import ClusterizationViewSet
from ej_conversations.api import CommentViewSet, ConversationViewSet, VoteViewSet
from ej_profiles.api import ProfileViewSet
from ej_integrations.api import OpinionComponentViewSet, RasaConversationViewSet
from ej_users.api import TokenViewSet, UsersViewSet
from rest_framework.routers import DefaultRouter
from drf_spectacular.views import SpectacularSwaggerView, SpectacularAPIView
from django.contrib.flatpages import views as flat_views
from django.conf.urls.i18n import i18n_patterns

unregister_admin.unregister_apps()

api_router = DefaultRouter()
api_router.register(
    r"rasa-conversations", RasaConversationViewSet, basename="v1-rasa-conversations"
)
api_router.register(
    r"opinion-component", OpinionComponentViewSet, basename="v1-opinion-component"
)
api_router.register(r"conversations", ConversationViewSet, basename="v1-conversations")
api_router.register(r"comments", CommentViewSet, basename="v1-comments")
api_router.register(r"votes", VoteViewSet, basename="v1-votes")
api_router.register(
    r"clusterizations", ClusterizationViewSet, basename="v1-clusterizations"
)
api_router.register(r"profiles", ProfileViewSet, basename="v1-profiles")
api_router.register(r"boards", BoardViewSet, basename="v1-boards")
api_router.register(r"users", UsersViewSet, basename="v1-users")
api_router.register(r"", TokenViewSet, basename="v1-auth")

log = logging.getLogger("ej")


def get_apps_dynamic_urls():
    """
    Allows apps to include new urls without editing ej/urls.py directly.
    In order to include new urls, the app must implements the get_app_urls method,
    inside the apps.py file. The method must return a namespaced path, for example:

    def get_app_urls(self):
        from my_app.views import View
        from django.urls import path

        urlpatterns = [path("path/", View.as_view(), name="path")]
        return path("customapp/", include(urlpatterns, namespace="customapp"))

    Checks ej_activation app, for example.
    """
    apps_urls = []
    for app_config in apps.app_configs:
        try:
            get_app_urls = getattr(apps.app_configs[app_config], "get_app_urls")
            apps_urls += [get_app_urls()]
            log.info(f"Including {app_config} URLs using get_apps_dynamic_urls()")
        except Exception:
            pass
    return apps_urls


def get_urlpatterns():
    fixes()

    patterns = [
        #
        # Basic authentication and authorization
        path(
            "",
            views.IndexView.as_view(),
            name="index",
        ),
        path(
            "info/styles/",
            views.InfoStylesView.as_view(),
            name="info-styles",
        ),
        path(
            "info/django-settings/",
            views.InfoDjangoSettingsView.as_view(),
            name="info-django-settings",
        ),
        path(
            "info/environment/",
            views.InfoEnvironView.as_view(),
            name="info-environ",
        ),
        path(
            "sw.js",
            views.ServiceWorkerView.as_view(),
            name="service-worker",
        ),
        path("", include("ej_users.urls.user", namespace="auth")),
        path("", include("ej_users.urls.account", namespace="account")),
        #
        #  Conversations and other EJ-specific routes
        path(
            "conversations/",
            include(
                "ej_conversations.urls.public_conversations", namespace="conversation"
            ),
        ),
        path(
            "comments/", include("ej_conversations.urls.comments", namespace="comments")
        ),
        #
        #  Profile URLS
        path("profile/", include("ej_profiles.urls", namespace="profile")),
        #
        #  Data visualization
        path("conversations/", include("ej_dataviz.urls", namespace="dataviz")),
        #
        # Administration Routes
        path("administration/", include("ej_admin.urls", namespace="administration")),
        #
        #  Global stereotype and cluster management
        path("conversations/", include("ej_clusters.urls.clusters", namespace="cluster")),
        path(
            "conversations/",
            include("ej_clusters.urls.stereotype_votes", namespace="stereotype-votes"),
        ),
        path(
            "stereotypes/",
            include("ej_clusters.urls.stereotypes", namespace="stereotypes"),
        ),
        #
        # Localization Routes
        path("change-language/", set_language, name="set_language"),
        #
        # Documentation in development mode
        re_path(r"^docs/$", serve, {"document_root": "build/docs", "path": "index.html"}),
        re_path(r"^docs/(?P<path>.*)$", serve, {"document_root": "build/docs/"}),
        #
        #  Admin
        *(
            [path(fix_url(settings.ADMIN_URL.lstrip("/")), admin.site.urls)]
            if apps.is_installed("django.contrib.admin")
            else ()
        ),
        path("usage", flat_views.flatpage, {"url": "usage"}, name="Terms of use"),
        # Boards URLs
        path("boards/", include("ej_boards.urls", namespace="boards")),
        #
        #  Allauth
        path("accounts/", include("allauth.urls")),
        #
        # REST API
        path("api/v1/", include(api_router.urls)),
        path("api/", include(rest_api.urls)),
        path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
        path(
            "api/v1/swagger/",
            SpectacularSwaggerView.as_view(url_name="schema"),
            name="swagger",
        ),
        # Static files for the dev server
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
        *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
        *get_apps_dynamic_urls(),
    ]

    if settings.DEBUG:
        # Pages for error codes
        patterns.extend(
            [
                path(
                    "error/400/",
                    default_views.bad_request,
                    kwargs={"exception": Exception("Bad Request!")},
                ),
                path(
                    "error/403/",
                    default_views.permission_denied,
                    kwargs={"exception": Exception("Permission Denied")},
                ),
                path(
                    "error/404/",
                    default_views.page_not_found,
                    kwargs={"exception": Exception("Page not Found")},
                ),
                path("error/500/", default_views.server_error),
                path("roles/", include("ej.roles.routes")),
            ]
        )

        if "debug_toolbar" in settings.INSTALLED_APPS:
            import debug_toolbar

            patterns.append(path("__debug__/", include(debug_toolbar.urls)))
    return patterns


def fix_url(url):
    return url.strip("/") + "/"


def fixes():
    if not apps.is_installed("ej_users"):
        user = get_user_model()
        try:
            rest_api.get_resource_info(user)
        except ImproperlyConfigured:
            rest_api(["username"])(user)


services.start_services(settings)
urlpatterns = get_urlpatterns()

src/ej_conecta_trabalhadores/urls.py
from django.urls import path

from .views import (
    ConectaConversationCommentView,
    EndParticipationView,
    RegisterProfileView,
    RegisterView,
    TourView,
    WelcomeView,
)

app_name = "ej_conecta_trabalhadores"
app_url = "conecta"
conversation_url = (
    "boards/<slug:board_slug>/conversations/<int:conversation_id>/<slug:slug>"
)

urlpatterns = [
    path(
        f"{app_url}/register",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        f"{app_url}/{conversation_url}/profile",
        RegisterProfileView.as_view(),
        name="profile",
    ),
    path(
        f"{app_url}/{conversation_url}/participe",
        WelcomeView.as_view(),
        name="welcome",
    ),
    path(
        f"{app_url}/{conversation_url}/encerrar",
        EndParticipationView.as_view(),
        name="end-participation",
    ),
    path(
        f"{app_url}/profile/tour/",
        TourView.as_view(),
        name="tour",
    ),
    path(
        f"{app_url}/profile/tour/?step=<step>",
        TourView.as_view(),
        name="tour",
    ),
    path(
        f"{app_url}/{conversation_url}/comments/new/",
        ConectaConversationCommentView.as_view(),
        name="new-comment",
    ),
]

src/ej_conecta_trabalhadores/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.flatpages.models import FlatPage
from django.core.exceptions import ValidationError
from django.db.models.fields import BLANK_CHOICE_DASH
from django.forms.forms import NON_FIELD_ERRORS
from django.utils.translation import gettext_lazy as _

from ej.forms import EjModelForm
from ej_conversations.forms import ConversationDateWidget
from ej_conversations.models.comment import Comment
from ej_profiles.enums import STATE_CHOICES
from ej_profiles.forms import (
    EDITABLE_FIELDS,
    EXCLUDE_EDITABLE_FIELDS,
    ProfileForm as DefaultProfileForm,
)

from .models import BOOLEAN_CHOICES, ConectaProfile
from .models import Conversation
from .validators import validate_is_numeric

User = get_user_model()


class ConversationForm(EjModelForm):
    """
    Form used to create and edit conversations.
    """

    comments_count = forms.IntegerField(initial=3, required=False)
    tags = forms.CharField(
        label=_("Tags"), help_text=_("Tags, separated by commas."), required=False
    )
    anonymous_votes_limit = forms.IntegerField(initial=0, min_value=0)

    class Meta:
        model = Conversation
        fields = [
            "title",
            "text",
            "is_promoted",
            "anonymous_votes_limit",
            "custom_fields_limit",
            "start_date",
            "end_date",
        ]
        help_texts = {
            "is_promoted": _("Place conversation in the main /conversations/ URL."),
            "is_hidden": _("Mark to make the conversation invisible."),
        }
        widgets = {
            "start_date": ConversationDateWidget,
            "end_date": ConversationDateWidget,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in ("tags", "text"):
            self.set_placeholder(field, self[field].help_text)
        if self.instance and self.instance.id is not None:
            self.fields["tags"].initial = ", ".join(
                self.instance.tags.values_list("name", flat=True)
            )

    def set_placeholder(self, field, value):
        self.fields[field].widget.attrs["placeholder"] = value

    def save(self, commit=True, board=None, **kwargs):
        if not board:
            raise ValidationError("Board field should not be empty")
        conversation = super().save(commit=False)
        conversation.board = board

        for k, v in kwargs.items():
            setattr(conversation, k, v)

        if commit:
            conversation.save()
            conversation.set_overdue()

            # Save tags on the database
            tags = self.cleaned_data["tags"].split(",")
            conversation.tags.set(tags, clear=True)

        return conversation

    def save_comments(
        self, author, check_limits=True, status=Comment.STATUS.approved, **kwargs
    ):
        """
        Save model, tags and comments.
        """
        conversation = self.save(author=author, **kwargs)

        # Create comments
        kwargs = {"status": status, "check_limits": check_limits}
        n = int(self.data["comments_count"])
        for i in range(n):
            name = f"comment-{i + 1}"
            value = self.data.get(name)
            if value:
                try:
                    conversation.create_comment(author, value, **kwargs)
                # Duplicate or empty comment...
                except ValidationError:
                    pass
        return conversation


class RegisterConversationTermsForm(EjModelForm):
    def __init__(self, *args, **kwargs):
        super(RegisterConversationTermsForm, self).__init__(*args, **kwargs)
        self.fields["agree_with_terms"].required = True
        self.fields["agree_with_privacy_policy"].required = True
        self.terms_content = {
            "agree_with_terms": self._get_flat_page("/usage/"),
            "agree_with_privacy_policy": self._get_flat_page("/privacy-policy/"),
        }

    def _get_flat_page(self, page_url: str):
        try:
            return FlatPage.objects.get(url=page_url).content
        except Exception:
            return ""

    class Meta:
        model = User
        help_texts = {
            "agree_with_terms": "Concordo com os termos de uso",
            "agree_with_privacy_policy": "Concordo com a politica de privacidade",
        }
        fields = ["agree_with_terms", "agree_with_privacy_policy"]


class RegisterConversationUserForm(forms.Form):
    email = forms.EmailField(label=_("email address"))

    def __init__(self, *args, **kwargs):
        super(RegisterConversationUserForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs["placeholder"] = "seuemail@mail.com"


class RegisterConversationProfileForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(RegisterConversationProfileForm, self).__init__(*args, **kwargs)
        self.fields["phone_number"].widget.attrs["placeholder"] = "(00) 00000 0000"

    phone_number = forms.CharField(
        label=_("phone number with whatsapp"),
        max_length=15,
        validators=[validate_is_numeric],
    )

    def clean_phone_number(self):
        phone_number = validate_is_numeric(self.cleaned_data["phone_number"])
        return phone_number


class ProfileForm(EjModelForm):
    """
    Form used only for creation of ConectaProfile
    """

    is_app_worker = forms.BooleanField(
        required=False,
        label=_("Do you consider yourself an app worker?"),
        widget=forms.RadioSelect(choices=BOOLEAN_CHOICES),
    )

    state = forms.ChoiceField(
        required=False,
        label=_("Which state do you live in?"),
        choices=BLANK_CHOICE_DASH + list(STATE_CHOICES),
    )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.fields["gender"].required = False
        self.fields["race"].required = False

    def clean(self):
        """
        method used for evaluating if at least one field of the form was filled
        """
        form_data = self.cleaned_data
        if not (
            form_data["gender"]
            or form_data["race"]
            or form_data["current_age"]
            or form_data["is_app_worker"]
            or form_data["state"]
        ):
            self._errors[NON_FIELD_ERRORS] = [_("You need to fill at least one field")]
        return form_data

    def save(self, commit=True, **kwargs):
        phone_number = self.user.profile.phone_number
        result = super().save(
            commit=commit,
            **kwargs,
            profile_ptr_id=self.user.profile.id,
            user_id=self.user.id,
            phone_number=phone_number,
        )
        return result

    class Meta:
        model = ConectaProfile
        fields = [
            "is_app_worker",
            "state",
            "gender",
            "race",
            "current_age",
            "phone_number",
        ]


class ConectaProfileForm(ProfileForm):
    """
    Form used only for creation of ConectaProfile without phone_number field
    """

    class Meta:
        model = ConectaProfile
        fields = ["is_app_worker", "state", "gender", "race", "current_age"]


class EditProfileForm(DefaultProfileForm):
    """
    User profile form
    """

    class Meta:
        model = ConectaProfile
        EDITABLE_FIELDS += ["is_app_worker", "current_age", "phone_number"]

        fields = [
            field for field in EDITABLE_FIELDS if field not in EXCLUDE_EDITABLE_FIELDS
        ]
        widgets = {
            "state": forms.Select(choices=STATE_CHOICES),
        }

src/ej_conecta_trabalhadores/templates/jinja2/ej_users/conecta-register.jinja2
<div id="comment-content-container">
    {% from "ej_conversations/includes/toast.jinja2" import dialog %}
    <div class="conecta-vote-card">{% include 'ej_conversations/includes/conversation-header.jinja2' %}</div>
    <div class="conecta-comment-grid">
        <div class="comment-card">
            <article>
                <div class="comment-card__progress comment-card__progress--left">
                    <div>
                        {{ _("You still can react to ") }}{{ "%d"|format(conversation.n_approved_comments - n_user_final_votes) }} {{ _(" proposals") }}
                    </div>
                </div>
                <form id="conecta-register-form"
                      class="conecta-register-form"
                      hx-post="{{ url("conecta:register") }}"
                      hx-target="body"
                      hx-swap="outerHTML">
                    {{ csrf_input }}
                    <div class="conecta-register-form__field">
                        {{ form_user }}
                        {% if form_user.errors %}{{ form_user.errors['email'] }}{% endif %}
                    </div>
                    <div class="conecta-register-form__field">
                        {{ form_profile }}
                        {% if form_profile.errors %}{{ form_profile.errors['phone_number'] }}{% endif %}
                    </div>
                    <div class="span2 conecta-register-form--centered">
                        {% for field in form_terms %}
                            <div>
                                {{ field }}<span onclick="show_{{ field.name }}_content()">{{ field.help_text }}</span>
                            </div>
                        {% endfor %}
                    </div>
                    <input type="hidden" name="conversation_id" value="{{ conversation.id }}">
                    <div class="margin-xauto conecta-register-form--centered">
                        <input hx-get="{{ url('conecta:end-participation', **conversation.get_url_kwargs() ) }}"
                               hx-target="#comment-content-container"
                               hx-swap="outerHTML"
                               type="submit"
                               value="{{ _("end participation") }}"
                               class="width-full is-primary conecta-register-form__button">
                        <input id="send-user-information"
                               type="submit"
                               name="submit"
                               value="{{ _("send informations") }}"
                               class="width-full is-primary">
                    </div>
                </form>
            </article>
        </div>
    </div>
    <div id="terms-modal">
        <div class="tour-backdrop"></div>
        <div class="tour-card">
            <div class="terms-modal__header">
                <div class="terms-modal__title"></div>
                <div onclick="hideModal()" class="terms-modal__close-icon">
                    <i class="fas fa-times"></i>
                </div>
            </div>
            <div class="terms-modal__body">
                <textarea readonly class="terms-modal__content"></textarea>
            </div>
        </div>
    </div>
    <script>
        $("#conecta-register-form").on("htmx:afterRequest", (event) => {
            if (event.target.id == 'conecta-register-form' && event.detail.successful){
                showConfirmationDialogFor("#register-dialog-confirmation");
            }
        });

        function show_agree_with_terms_content() {
            $("#terms-modal")[0].style.visibility = "visible";
            let content = `{{ form_terms.terms_content.agree_with_terms|safe }}`;
            $(".terms-modal__content")[0].textContent = content;
            $(".terms-modal__title")[0].textContent = "Termos de uso";
        }

        function show_agree_with_privacy_policy_content() {
            $("#terms-modal")[0].style.visibility = "visible";
            let content = `{{ form_terms.terms_content.agree_with_privacy_policy|safe }}`;
            $(".terms-modal__content")[0].textContent  = content;
            $(".terms-modal__title")[0].textContent = "Política de privacidade";
        }

        function hideModal() {
            $("#terms-modal")[0].style.visibility = "hidden";
        }

        $("#id_phone_number").on("input", function () {
            console.log(event);
            const phoneMask = (value) => {
                if (!value) return ""
                value = value.replace(/\D/g,'')
                value = value.replace(/(\d{2})(\d)/,"($1) $2")
                value = value.replace(/(\d)(\d{4})$/,"$1-$2")
                return value
            }
            let input = event.target
            input.value = phoneMask(input.value)
        })
    </script>
</div>

src/ej_conecta_trabalhadores/templates/jinja2/ej_users/login.jinja2
{% extends 'base.jinja2' %}
{% set next = ('?next=' + next if next else '') %}
{% set hide_menu = false -%}
{% set social_buttons = false -%}
{% block content %}
    {% block form_data %}
        <form method="post"
              class="login-form pad-t3 form-narrow"
              aria-label="{{ _("Login form") }}"
              aria-live="assertive">
            {{ csrf_input }}
            <div class="login-form__logo">
                <img src="{{ static("/img/logo/logo-dark.png") }}" alt="ej dark logo">
            </div>
            <div class="login-form__input">
                <label class="login-form__label">{{ form.email.label }}</label>
                {{ form.email }}
            </div>
            <div class="login-form__input">
                <label class="login-form__label">{{ form.password.label }}</label>
                {{ form.password }}
                {{ form.non_field_errors() }}
            </div>
            <div class="login-form__button-container">
                <a href="{{ url("auth:recover-password") }}"
                   class="underline login-form__reset-password">{{ _("I forgot my password") }}</a>
                <input type="submit"
                       name="submit"
                       value="{{ _("Login") }}"
                       class="width-full is-primary login-form__submit-button">
            </div>
        </form>
        {% if social_buttons|default(false) %}
            {{ social_js }}
            {% include 'ej_users/includes/social-buttons.jinja2' %}
        {% endif %}
        <script src="/static/js/vote-from-template.js"></script>
    {% endblock %}
    {% block form_footer %}
        <hr class="margin-auto register-redirection__hr">
        <div class="register-redirection">
            <img src="{{ static("/img/login/login.svg") }}" alt="ej cat logo">
            <div class="register-redirection__button">
                <span>{{ _(settings.EJ_REGISTER_TEXT) }}</span>
                <a class="button"
                   href="{{ url("auth:register") + next }}"
                   secondary
                   aria-label="{{ _("Create your account!") }}">{{ _("Register now!") }}</a>
            </div>
        </div>
    {% endblock %}
{% endblock %}

src/ej_conecta_trabalhadores/templates/jinja2/ej_users/register.jinja2
{% extends 'base.jinja2' %}
{% set hide_menu = false -%}
{% set social_buttons = false -%}
{% set next = ('?next=' + next if next else '') %}
{% block content %}
    {% block form_data %}
        <div class="content-grid register-form">
            <form method="post">
                <div class="register-form__title">
                    <h1 class="text-accent" aria-hidden="true">{{ _("Register new user") }}</h1>
                    <img class="register-form__image" src="{{ static("/img/login/login.svg") }}" style="left: 1rem" alt="">
                </div>
                {{ csrf_input }}
                <div class="register-form__input">
                    <label class="login-form__label">{{ form.name.label }}</label>
                    {{ form.name }}
                </div>
                {% if form.email.errors %}
                    <div class="register-form input-error">
                        <label class="login-form__label">{{ form.email.help_text }}</label>
                        {{ form.email }}
                        {{ form.email.errors }}
                    </div>
                {% else %}
                    <div class="register-form register-form__input">
                        <label class="login-form__label">{{ form.email.help_text }}</label>
                        {{ form.email }}
                    </div>
                {% endif %}
                {% if form.password.errors %}
                    <div class="register-form input-error">
                        <label class="login-form__label">{{ form.password.label }}</label>
                        {{ form.password }}
                        {{ form.password.errors }}
                    </div>
                    <div class="register-form input-error">
                        <label class="login-form__label">{{ form.password_confirm.label }}</label>
                        {{ form.password_confirm }}
                    </div>
                {% else %}
                    <div class="register-form register-form__input">
                        <label class="login-form__label">{{ form.password.label }}</label>
                        {{ form.password }}
                    </div>
                    <div class="register-form register-form__input">
                        <label class="login-form__label">{{ form.password_confirm.label }}</label>
                        {{ form.password_confirm }}
                    </div>
                {% endif %}
                <div class="register-form--full-width">
                    <span class="register-form__label">{{ _("When registering, you agreed to the ") }}</span>
                    <a target="_blank" class="text-accent" href="/usage">{{ form.agree_with_terms.label }}</a>
                    {{ _("and") }}
                    <a target="_blank" class="text-accent" href="/privacy-policy">{{ form.agree_with_privacy_policy.label }}.</a>
                </div>
                <div class="register-form__buttons">
                    {% if social_buttons|default(false) %}
                        {{ social_js }}
                        {% include 'ej_users/includes/social-buttons.jinja2' %}
                    {% endif %}
                    <div>
                        <input type="submit"
                               name="submit"
                               value="{{ _("Register") }}"
                               class="width-full is-primary register-form__submit-button">
                    </div>
                </div>
            </form>
        </div>
        <script src="/static/js/vote-from-template.js"></script>
    {% endblock %}
    {% block form_footer %}
        <hr class="margin-auto register-redirection__hr">
        <div class="margin-b2 register-redirection">
            <img src="{{ static("/img/login/login.svg") }}" alt="ej cat logo">
            <div class="register-redirection__button">
                <span>{{ _("Already has an account?") }}</span>
                <a class="button"
                   href="{{ url("auth:login") + next }}"
                   secondary
                   aria-label="{{ _("Already has an account?") }}">{{ _("Login") }}</a>
            </div>
        </div>
    {% endblock %}
{% endblock %}